// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: currency/currency.proto

package pbCurrency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPriceInfosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceInfosRequest) Reset() {
	*x = GetPriceInfosRequest{}
	mi := &file_currency_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceInfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceInfosRequest) ProtoMessage() {}

func (x *GetPriceInfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceInfosRequest.ProtoReflect.Descriptor instead.
func (*GetPriceInfosRequest) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{0}
}

type RefetchPriceInfosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefetchPriceInfosRequest) Reset() {
	*x = RefetchPriceInfosRequest{}
	mi := &file_currency_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefetchPriceInfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefetchPriceInfosRequest) ProtoMessage() {}

func (x *RefetchPriceInfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefetchPriceInfosRequest.ProtoReflect.Descriptor instead.
func (*RefetchPriceInfosRequest) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{1}
}

type RefetchPriceInfosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefetchPriceInfosResponse) Reset() {
	*x = RefetchPriceInfosResponse{}
	mi := &file_currency_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefetchPriceInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefetchPriceInfosResponse) ProtoMessage() {}

func (x *RefetchPriceInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefetchPriceInfosResponse.ProtoReflect.Descriptor instead.
func (*RefetchPriceInfosResponse) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{2}
}

func (x *RefetchPriceInfosResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefetchPriceInfosResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPriceInfosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceInfosResponse) Reset() {
	*x = GetPriceInfosResponse{}
	mi := &file_currency_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceInfosResponse) ProtoMessage() {}

func (x *GetPriceInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceInfosResponse.ProtoReflect.Descriptor instead.
func (*GetPriceInfosResponse) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GetPriceInfosResponse) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_currency_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{4}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Currency) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_currency_currency_proto protoreflect.FileDescriptor

const file_currency_currency_proto_rawDesc = "" +
	"\n" +
	"\x17currency/currency.proto\x12\bcurrency\"\x16\n" +
	"\x14GetPriceInfosRequest\"\x1a\n" +
	"\x18RefetchPriceInfosRequest\"O\n" +
	"\x19RefetchPriceInfosResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x15GetPriceInfosResponse\x122\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x12.currency.CurrencyR\n" +
	"currencies\"H\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date2\xc5\x01\n" +
	"\x0fCurrencyService\x12R\n" +
	"\rGetPriceInfos\x12\x1e.currency.GetPriceInfosRequest\x1a\x1f.currency.GetPriceInfosResponse\"\x00\x12^\n" +
	"\x11RefetchPriceInfos\x12\".currency.RefetchPriceInfosRequest\x1a#.currency.RefetchPriceInfosResponse\"\x00B2Z0crypto-platform/shared/proto/currency;pbCurrencyb\x06proto3"

var (
	file_currency_currency_proto_rawDescOnce sync.Once
	file_currency_currency_proto_rawDescData []byte
)

func file_currency_currency_proto_rawDescGZIP() []byte {
	file_currency_currency_proto_rawDescOnce.Do(func() {
		file_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_currency_proto_rawDesc), len(file_currency_currency_proto_rawDesc)))
	})
	return file_currency_currency_proto_rawDescData
}

var file_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_currency_currency_proto_goTypes = []any{
	(*GetPriceInfosRequest)(nil),      // 0: currency.GetPriceInfosRequest
	(*RefetchPriceInfosRequest)(nil),  // 1: currency.RefetchPriceInfosRequest
	(*RefetchPriceInfosResponse)(nil), // 2: currency.RefetchPriceInfosResponse
	(*GetPriceInfosResponse)(nil),     // 3: currency.GetPriceInfosResponse
	(*Currency)(nil),                  // 4: currency.Currency
}
var file_currency_currency_proto_depIdxs = []int32{
	4, // 0: currency.GetPriceInfosResponse.currencies:type_name -> currency.Currency
	0, // 1: currency.CurrencyService.GetPriceInfos:input_type -> currency.GetPriceInfosRequest
	1, // 2: currency.CurrencyService.RefetchPriceInfos:input_type -> currency.RefetchPriceInfosRequest
	3, // 3: currency.CurrencyService.GetPriceInfos:output_type -> currency.GetPriceInfosResponse
	2, // 4: currency.CurrencyService.RefetchPriceInfos:output_type -> currency.RefetchPriceInfosResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_currency_currency_proto_init() }
func file_currency_currency_proto_init() {
	if File_currency_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_currency_proto_rawDesc), len(file_currency_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_currency_proto_goTypes,
		DependencyIndexes: file_currency_currency_proto_depIdxs,
		MessageInfos:      file_currency_currency_proto_msgTypes,
	}.Build()
	File_currency_currency_proto = out.File
	file_currency_currency_proto_goTypes = nil
	file_currency_currency_proto_depIdxs = nil
}
