// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: currency/currency.proto

package pbCurrency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyService_GetPriceInfos_FullMethodName     = "/currency.CurrencyService/GetPriceInfos"
	CurrencyService_RefetchPriceInfos_FullMethodName = "/currency.CurrencyService/RefetchPriceInfos"
)

// CurrencyServiceClient is the client API for CurrencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyServiceClient interface {
	GetPriceInfos(ctx context.Context, in *GetPriceInfosRequest, opts ...grpc.CallOption) (*GetPriceInfosResponse, error)
	RefetchPriceInfos(ctx context.Context, in *RefetchPriceInfosRequest, opts ...grpc.CallOption) (*RefetchPriceInfosResponse, error)
}

type currencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyServiceClient(cc grpc.ClientConnInterface) CurrencyServiceClient {
	return &currencyServiceClient{cc}
}

func (c *currencyServiceClient) GetPriceInfos(ctx context.Context, in *GetPriceInfosRequest, opts ...grpc.CallOption) (*GetPriceInfosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPriceInfosResponse)
	err := c.cc.Invoke(ctx, CurrencyService_GetPriceInfos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) RefetchPriceInfos(ctx context.Context, in *RefetchPriceInfosRequest, opts ...grpc.CallOption) (*RefetchPriceInfosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefetchPriceInfosResponse)
	err := c.cc.Invoke(ctx, CurrencyService_RefetchPriceInfos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyServiceServer is the server API for CurrencyService service.
// All implementations must embed UnimplementedCurrencyServiceServer
// for forward compatibility.
type CurrencyServiceServer interface {
	GetPriceInfos(context.Context, *GetPriceInfosRequest) (*GetPriceInfosResponse, error)
	RefetchPriceInfos(context.Context, *RefetchPriceInfosRequest) (*RefetchPriceInfosResponse, error)
	mustEmbedUnimplementedCurrencyServiceServer()
}

// UnimplementedCurrencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyServiceServer struct{}

func (UnimplementedCurrencyServiceServer) GetPriceInfos(context.Context, *GetPriceInfosRequest) (*GetPriceInfosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPriceInfos not implemented")
}
func (UnimplementedCurrencyServiceServer) RefetchPriceInfos(context.Context, *RefetchPriceInfosRequest) (*RefetchPriceInfosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefetchPriceInfos not implemented")
}
func (UnimplementedCurrencyServiceServer) mustEmbedUnimplementedCurrencyServiceServer() {}
func (UnimplementedCurrencyServiceServer) testEmbeddedByValue()                         {}

// UnsafeCurrencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyServiceServer will
// result in compilation errors.
type UnsafeCurrencyServiceServer interface {
	mustEmbedUnimplementedCurrencyServiceServer()
}

func RegisterCurrencyServiceServer(s grpc.ServiceRegistrar, srv CurrencyServiceServer) {
	// If the following call panics, it indicates UnimplementedCurrencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyService_ServiceDesc, srv)
}

func _CurrencyService_GetPriceInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).GetPriceInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_GetPriceInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).GetPriceInfos(ctx, req.(*GetPriceInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_RefetchPriceInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefetchPriceInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).RefetchPriceInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_RefetchPriceInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).RefetchPriceInfos(ctx, req.(*RefetchPriceInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyService_ServiceDesc is the grpc.ServiceDesc for CurrencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "currency.CurrencyService",
	HandlerType: (*CurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPriceInfos",
			Handler:    _CurrencyService_GetPriceInfos_Handler,
		},
		{
			MethodName: "RefetchPriceInfos",
			Handler:    _CurrencyService_RefetchPriceInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currency/currency.proto",
}
