// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: crypto/crypto.proto

package pbCrypto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPriceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	IsRefetch     bool                   `protobuf:"varint,2,opt,name=is_refetch,json=isRefetch,proto3" json:"is_refetch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceInfoRequest) Reset() {
	*x = GetPriceInfoRequest{}
	mi := &file_crypto_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceInfoRequest) ProtoMessage() {}

func (x *GetPriceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPriceInfoRequest) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *GetPriceInfoRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPriceInfoRequest) GetIsRefetch() bool {
	if x != nil {
		return x.IsRefetch
	}
	return false
}

type GetPriceInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceInfos    []*PriceInfo           `protobuf:"bytes,1,rep,name=price_infos,json=priceInfos,proto3" json:"price_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceInfoResponse) Reset() {
	*x = GetPriceInfoResponse{}
	mi := &file_crypto_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceInfoResponse) ProtoMessage() {}

func (x *GetPriceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPriceInfoResponse) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *GetPriceInfoResponse) GetPriceInfos() []*PriceInfo {
	if x != nil {
		return x.PriceInfos
	}
	return nil
}

type PriceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	LastUpdatedAt string                 `protobuf:"bytes,3,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Open          float64                `protobuf:"fixed64,7,opt,name=open,proto3" json:"open,omitempty"`
	Close         float64                `protobuf:"fixed64,8,opt,name=close,proto3" json:"close,omitempty"`
	BaseVolume    float64                `protobuf:"fixed64,9,opt,name=base_volume,json=baseVolume,proto3" json:"base_volume,omitempty"`
	QuoteVolume   float64                `protobuf:"fixed64,10,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`
	Change        float64                `protobuf:"fixed64,11,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,12,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceInfo) Reset() {
	*x = PriceInfo{}
	mi := &file_crypto_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceInfo) ProtoMessage() {}

func (x *PriceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceInfo.ProtoReflect.Descriptor instead.
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *PriceInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceInfo) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PriceInfo) GetLastUpdatedAt() string {
	if x != nil {
		return x.LastUpdatedAt
	}
	return ""
}

func (x *PriceInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceInfo) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *PriceInfo) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PriceInfo) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *PriceInfo) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *PriceInfo) GetBaseVolume() float64 {
	if x != nil {
		return x.BaseVolume
	}
	return 0
}

func (x *PriceInfo) GetQuoteVolume() float64 {
	if x != nil {
		return x.QuoteVolume
	}
	return 0
}

func (x *PriceInfo) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *PriceInfo) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

var File_crypto_crypto_proto protoreflect.FileDescriptor

const file_crypto_crypto_proto_rawDesc = "" +
	"\n" +
	"\x13crypto/crypto.proto\x12\x06crypto\"L\n" +
	"\x13GetPriceInfoRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"is_refetch\x18\x02 \x01(\bR\tisRefetch\"J\n" +
	"\x14GetPriceInfoResponse\x122\n" +
	"\vprice_infos\x18\x01 \x03(\v2\x11.crypto.PriceInfoR\n" +
	"priceInfos\"\xd0\x02\n" +
	"\tPriceInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12&\n" +
	"\x0flast_updated_at\x18\x03 \x01(\tR\rlastUpdatedAt\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x12\n" +
	"\x04open\x18\a \x01(\x01R\x04open\x12\x14\n" +
	"\x05close\x18\b \x01(\x01R\x05close\x12\x1f\n" +
	"\vbase_volume\x18\t \x01(\x01R\n" +
	"baseVolume\x12!\n" +
	"\fquote_volume\x18\n" +
	" \x01(\x01R\vquoteVolume\x12\x16\n" +
	"\x06change\x18\v \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\f \x01(\x01R\rchangePercent2\\\n" +
	"\rCryptoService\x12K\n" +
	"\fGetPriceInfo\x12\x1b.crypto.GetPriceInfoRequest\x1a\x1c.crypto.GetPriceInfoResponse\"\x00B.Z,crypto-platform/shared/proto/crypto;pbCryptob\x06proto3"

var (
	file_crypto_crypto_proto_rawDescOnce sync.Once
	file_crypto_crypto_proto_rawDescData []byte
)

func file_crypto_crypto_proto_rawDescGZIP() []byte {
	file_crypto_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_crypto_proto_rawDesc), len(file_crypto_crypto_proto_rawDesc)))
	})
	return file_crypto_crypto_proto_rawDescData
}

var file_crypto_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_crypto_crypto_proto_goTypes = []any{
	(*GetPriceInfoRequest)(nil),  // 0: crypto.GetPriceInfoRequest
	(*GetPriceInfoResponse)(nil), // 1: crypto.GetPriceInfoResponse
	(*PriceInfo)(nil),            // 2: crypto.PriceInfo
}
var file_crypto_crypto_proto_depIdxs = []int32{
	2, // 0: crypto.GetPriceInfoResponse.price_infos:type_name -> crypto.PriceInfo
	0, // 1: crypto.CryptoService.GetPriceInfo:input_type -> crypto.GetPriceInfoRequest
	1, // 2: crypto.CryptoService.GetPriceInfo:output_type -> crypto.GetPriceInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_crypto_crypto_proto_init() }
func file_crypto_crypto_proto_init() {
	if File_crypto_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_crypto_proto_rawDesc), len(file_crypto_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_crypto_proto_depIdxs,
		MessageInfos:      file_crypto_crypto_proto_msgTypes,
	}.Build()
	File_crypto_crypto_proto = out.File
	file_crypto_crypto_proto_goTypes = nil
	file_crypto_crypto_proto_depIdxs = nil
}
